# Setup
title:               Rahul Yumlembam
tagline:             'Machine Story'
description:         'A no-nonsense blog themeâ€”like a well-tuned ML model, minimal overfitting, maximum readability.'
url:                 'https://github.com/Yumlembam/Yumlembam.github.io'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Rahul Yumlembam
  url:               'https://github.com/Yumlembam/Yumlembam.github.io'
  email:             rahul@example.com  # Update with your real email if needed

# Plugins
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-9E77406NL6
